language: node_js
node_js: 8

sudo: required
services:
  - docker

before_install:
  - docker build -t sauliusonis/docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true sauliusonis/docker-react-travis npm run test