language: node_js
node_js: 8

sudo: required
services:
  - docker

before_install:
  - docker build -t sauliusonis/docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true sauliusonis/docker-react-travis npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-travis"
  env: "Dockerreacttravis-env"
  bucket_name: "elasticbeanstalk-eu-west-1-467667289006"
  bucket_path: "docker-react-travis"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
